Gem: Update pry to 0.14.x (#1322)
To fix following error when run the spec with Ruby 3.2.0-dev, this patch will update pry gem version.

```
$ ruby -v
ruby 3.2.0dev (2022-03-19T05:33:04Z master fafa40997e) [x86_64-linux]

$ bundle exec rake
/usr/bin/gmake install target_prefix=
/usr/bin/install -c -m 0755 RMagick2.so /home/watson/prj/rmagick/lib
cp tmp/x86_64-linux/RMagick2/3.2.0/RMagick2.so tmp/x86_64-linux/stage/lib/RMagick2.so
/home/watson/.rbenv/versions/3.2.0-dev/bin/ruby -I/home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-core-3.11.0/lib:/home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-support-3.11.0/lib /home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: require 'pry'

NameError:
  undefined method `=~' for class `Pry::Code'
# ./spec/spec_helper.rb:5:in `require'
# ./spec/spec_helper.rb:5:in `<top (required)>'
No examples found.


Finished in 0.00002 seconds (files took 0.06842 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/home/watson/.rbenv/versions/3.2.0-dev/bin/ruby -I/home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-core-3.11.0/lib:/home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-support-3.11.0/lib /home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```