check that GetImageChannelEntropy() is implemented in ImageMagick
GetImageChannelEntropy() was implemented at ImageMagick 6.9.0-0.

If RMagick was compiled with older ImageMagick 6,
it will cause a following error when it looks up GetImageChannelEntropy symbol.

```
dyld: lazy symbol binding failed: Symbol not found: _GetImageChannelEntropy
  Referenced from: /Users/watson/prj/rmagick/lib/RMagick2.bundle
  Expected in: flat namespace

dyld: Symbol not found: _GetImageChannelEntropy
  Referenced from: /Users/watson/prj/rmagick/lib/RMagick2.bundle
  Expected in: flat namespace
```