Remove unnecessary minimum ruby version check (#1637)
If use old ruby to install, it show the following message.

```
$ gem install ./rmagick-6.0.1.gem
ERROR:  Error installing ./rmagick-6.0.1.gem:
	There are no versions of rmagick (= 6.0.1) compatible with your Ruby & RubyGems
	rmagick requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```

It is in https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/lib/rubygems/request_set.rb#L199

The supported ruby version check is invoked at rubygems system at first before calling assert_minimum_ruby_version!.

So, this patch will remove redundant version check.