CI: Add path for glib on macOS
liblqr requires glib, however, it seems that it breaks dependency in github runner.

Sometimes, it causes the following error.
```
/usr/local/Cellar/liblqr/0.4.2_1/include/lqr-1/lqr.h:26:10: fatal error: 'glib.h' file not found
#include <glib.h>
         ^~~~~~~~
```