Suppress exception at installation if ImageMagick is not installed
If ImageMagick is not installed, installer show the following exception:

```
$ ruby extconf.rb
checking for brew... yes
/Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:504:in `parse_pc': .pc doesn't exist: <MagickCore> (PackageConfig::NotFoundError)
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:348:in `declaration'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:289:in `requires'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:545:in `block in required_packages'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:374:in `collect_requires'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:544:in `required_packages'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:452:in `collect_libs'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:310:in `libs'
	from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:591:in `libs'
	from extconf.rb:300:in `assert_has_dev_libs!'
	from extconf.rb:281:in `assert_can_compile!'
	from extconf.rb:48:in `initialize'
	from extconf.rb:408:in `new'
	from extconf.rb:408:in `<main>'
```

This patch will show the expected error message:

```
$ ruby extconf.rb
checking for brew... yes

ERROR: Can't install RMagick 6.0.1.
Can't find the ImageMagick library or one of the dependent libraries.
Check the mkmf.log file for more detailed information.
```